project:
  type: book
  output-dir: book

book:
  title: "Grampian Networked Data Lab"
  author: 
    - Jess Butler, Lead Data Scientist
    - Frank Popham, Senior Specialist Analyst
  date: today
  chapters:
    - index.qmd
    - project.qmd
    - workflow.qmd
    - data_sources.qmd
    - code.qmd
    - research.qmd
    - people.qmd
    - peer_groups.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


number-depth: 1
search: true
cover-image: isaac-smith-6EnTPvPPL6I-unsplash.jpg
